[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = "4.5.34"
crossterm = "0.29.0"
env_logger = "0.11.7"
log = "0.4.27"
serde_cbor = "0.11.2"
shared = { path = "../shared" }
tokio = { version = "1.44.2", features = ["full"] }
